### ISSUE TITLE
Add CONTRIBUTION.md Page with guildlines

### ISSUE THREAD

**Issue by jinnabaalu** [JinnaBalu/S3DockerTool#2]
- Add generic contribution md page

**Comment by Captain-DarkO** [comment]
On it

**Comment by jinnabaalu** [comment]
Need the generic steps on for contribution
fork
clone
push
create the PR 
this steps need to be explained clearly

**Comment by Captain-DarkO** [comment]
Oh you mean contributing guidelines

**Comment by jinnabaalu** [comment]
Yes, thanks for correcting me.

**Comment by Captain-DarkO** [comment]
Cheers, please review my PR. :)
